# Check https://circleci.com/docs/2.0/ for more details
# for config.yml syntax see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# for testing on Windows
orbs:
  win: circleci/windows@5

executors:
  mac:
    macos:
      xcode: "14.3.1"
    resource_class: macos.m1.medium.gen1

jobs:
  mac-test:
    executor: mac

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      - run: npm install cypress
      - run: npm run cypress:info
      - run: npm run cypress:version
      - run: npm run cypress:run
      - run: npm run cypress:cache:list

  linux-test:
    docker:
      # find Docker image at https://github.com/cypress-io/cypress-docker-images
      - image: cypress/base:18.16.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      - run: npm install cypress
      - run: npm run cypress:info
      - run: npm run cypress:version
      - run: CYPRESS_INTERNAL_ENV=staging CYPRESS_PROJECT_ID=3ik9rd CYPRESS_RECORD_KEY=$CYPRESS_RECORD_KEY_STAGING_TYLER_TESTS npm run cypress:run -- --record
      - run: npm run cypress:cache:list

  win-test:
    working_directory: ~/app
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - checkout
      - run: npm ci
      - run: npm install cypress
      - run: npm run cypress:info
      - run: npm run cypress:version
      - run: npm run cypress:cache:list

  verify-linux-test:
    docker:
      # find Docker image at https://github.com/cypress-io/cypress-docker-images
      - image: cypress/base:18.16.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      - run: npm install --force https://cdn.cypress.io/extract-cloud-results/beta/v1/extract-cloud-results.tgz && CYPRESS_INTERNAL_ENV=staging CYPRESS_PROJECT_ID=3ik9rd CYPRESS_RECORD_KEY=$CYPRESS_RECORD_KEY_STAGING_TYLER_TESTS node ./scripts/verifyAccessibilityResults.js

workflows:
  version: 2
  tests:
    jobs:
      - win-test:
          context: test-runner:commit-status-checks
      - linux-test:
          context: test-runner:commit-status-checks
      - mac-test:
          context: test-runner:commit-status-checks
      - verify-linux-test:
          requires: [linux-test]
          context: test-runner:commit-status-checks

