# Check https://circleci.com/docs/2.0/ for more details
# for config.yml syntax see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# for testing on Windows
# https://circleci.com/docs/2.0/hello-world-windows/
orbs:
  win: circleci/windows@1

executors:
  mac:
    macos:
      xcode: "13.0.0"

jobs:
  mac-test:
    executor: mac

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      - run: npm install cypress
      - run: npm run cypress:info
      - run: npm run cypress:version
      - run: npm run cypress:run
      - run: npm run cypress:cache:list

  linux-test:
    docker:
      # find Docker image at https://github.com/cypress-io/cypress-docker-images
      - image: cypress/base:16.18.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      - run: npm install cypress
      - run: npm run cypress:info
      - run: npm run cypress:version
      - run: npm run cypress:run
      - run: npm run cypress:cache:list

  win-test:
    working_directory: ~/app
    executor:
      name: win/vs2019
      shell: bash.exe
    steps:
      - checkout
      - run: npm ci
      - run: npm install cypress
      - run: npm run cypress:info
      - run: npm run cypress:version
      - run: npm run cypress:run
      - run: npm run cypress:cache:list

workflows:
  version: 2
  tests:
    jobs:
      - win-test:
          context: test-runner:commit-status-checks
      - linux-test:
          context: test-runner:commit-status-checks
      - mac-test:
          context: test-runner:commit-status-checks
